version: '3.9'

services:
  app:
    build:
      context: ./docker/app
    container_name: ps91-app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      # Utilisé par PrestaShop pendant l'installation
      PS_DEV_MODE: "1"
      APACHE_DOCUMENT_ROOT: /var/www/html/public
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWORD: prestashop
      DB_PREFIX: ps_
    volumes:
      # Code PrestaShop (persistant):
      - ./prestashop:/var/www/html
      # Votre module (ce dépôt) mappé dans le dossier modules du shop (nom technique sans tirets):
      - ./src:/var/www/html/modules/prestashop_bulk_action
    networks:
      - psnet

  db:
    image: mysql:8.0
    container_name: ps91-db
    command: ["--default-authentication-plugin=mysql_native_password", "--sql_mode=", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - psnet

  phpmyadmin:
    image: phpmyadmin:5
    container_name: ps91-pma
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: prestashop
      PMA_PASSWORD: prestashop
    ports:
      - "8081:80"
    networks:
      - psnet

volumes:
  db_data:

networks:
  psnet:
    driver: bridge
