prestashop_bulk_action_make_available:
  path: /prestashop-bulk-action/make-available
  methods: [POST]
  options:
    expose: true
  defaults:
    _controller: 'PrestaShop\Module\PrestashopBulkAction\Controller\Admin\BulkActionController::makeAvailableAction'

prestashop_bulk_action_make_unavailable:
  path: /prestashop-bulk-action/make-unavailable
  methods: [POST]
  options:
    expose: true
  defaults:
    _controller: 'PrestaShop\Module\PrestashopBulkAction\Controller\Admin\BulkActionController::makeUnavailableAction'
